#!/bin/sh
set -eu

echo "---------- Git hook: pre-commit ----------"

# Biome (lint, format, imports)
echo ">>> [1/2] Running Biome on frontend"
yarn biome:check

# Typescript (type checking)
echo ">>> [2/2] Compiling Typescript"
yarn tsc

echo "------------------------------------------"
