import { SkillName } from "@/features/skills/constants";
import type { Project } from "./types";

export const projectsData: Project[] = [
  {
    id: 15,
    name: "grove",
    description:
      "macOS sidebar for managing git worktrees and monitoring Claude Code sessions across your workspaces.",
    githubUrl: "https://github.com/Jordan-Kowal/grove",
    websiteUrl: undefined,
    screenshots: [
      "screenshots/grove-1.png",
      "screenshots/grove-2.png",
      "screenshots/grove-3.png",
      "screenshots/grove-4.png",
      "screenshots/grove-5.png",
    ],
    deprecated: false,
    skills: [
      SkillName.TypeScript,
      SkillName.Solid,
      SkillName.Wails,
      SkillName.Go,
    ],
  },
  {
    id: 14,
    name: "click-launch",
    description:
      "Desktop app for managing your local dev stack — configure once, launch everything with a click.",
    githubUrl: "https://github.com/Jordan-Kowal/click-launch",
    websiteUrl: undefined,
    screenshots: [
      "screenshots/click-launch-1.png",
      "screenshots/click-launch-2.png",
      "screenshots/click-launch-3.png",
    ],
    deprecated: false,
    skills: [
      SkillName.TypeScript,
      SkillName.Solid,
      SkillName.Wails,
      SkillName.Go,
    ],
  },
  {
    id: 11,
    name: "pipe-operator",
    description: "Elixir's pipe operator in Python.",
    githubUrl: "https://github.com/Jordan-Kowal/pipe-operator",
    websiteUrl: "https://pypi.org/project/pipe-operator/",
    screenshots: [],
    deprecated: false,
    skills: [SkillName.Python],
  },
  {
    id: 5,
    name: "personal-website",
    description:
      "You are viewing it right now. My personal static website made with Vite, SolidJS, and DaisyUI.",
    githubUrl: "https://github.com/Jordan-Kowal/personal-website",
    websiteUrl: "https://jordan-kowal.github.io/personal-website/",
    screenshots: ["screenshots/personal-website.png"],
    deprecated: false,
    skills: [SkillName.TypeScript, SkillName.SolidJS],
  },
  {
    id: 3,
    name: "django-react-starter",
    description:
      "Django-React starter with Docker support for fast and easy web development.",
    githubUrl: "https://github.com/Jordan-Kowal/django-react-starter",
    websiteUrl: undefined,
    screenshots: [
      "screenshots/starter-login.png",
      "screenshots/starter-homepage.png",
      "screenshots/starter-settings.png",
    ],
    deprecated: true,
    skills: [
      SkillName.Python,
      SkillName.Django,
      SkillName.TypeScript,
      SkillName.React,
      SkillName.PostgreSQL,
      SkillName.Docker,
    ],
  },
  {
    id: 12,
    name: "django-utils-kit",
    description: "Various utilities for working with Django and DRF.",
    githubUrl: "https://github.com/Jordan-Kowal/django-utils-kit",
    websiteUrl: "https://pypi.org/project/django-utils-kit/",
    screenshots: [],
    deprecated: true,
    skills: [SkillName.Python, SkillName.Django],
  },
  {
    id: 13,
    name: "django-meilisearch-indexer",
    description: "Meilisearch indexer for django models and related utilities.",
    githubUrl: "https://github.com/Jordan-Kowal/django-meilisearch-indexer",
    websiteUrl: "https://pypi.org/project/django-meilisearch-indexer/",
    screenshots: [],
    deprecated: true,
    skills: [SkillName.Python, SkillName.Django, SkillName.Meilisearch],
  },
  {
    id: 2,
    name: "jkscript",
    description: "Personal library with ES6 JavaScript utilities.",
    githubUrl: "https://github.com/Jordan-Kowal/jkscript",
    websiteUrl: "https://www.npmjs.com/package/jcscript",
    screenshots: [],
    deprecated: true,
    skills: [SkillName.TypeScript],
  },
  {
    id: 6,
    name: "challenges",
    description:
      "Snippets from various challenges, hackathons, and competitions.",
    githubUrl: "https://github.com/Jordan-Kowal/challenges",
    websiteUrl: undefined,
    screenshots: [],
    deprecated: true,
    skills: [SkillName.Python, SkillName.Elixir],
  },
  {
    id: 1,
    name: "jklib",
    description:
      "Package with useful snippets for Django and general Python development.",
    githubUrl: "https://github.com/Jordan-Kowal/jklib",
    websiteUrl: "https://pypi.org/project/jklib/",
    screenshots: [],
    deprecated: true,
    skills: [SkillName.Python, SkillName.Django],
  },
  {
    id: 4,
    name: "enseirb-schedule-notifier",
    description:
      "School schedule with improved UI and automatic notifications on schedule changes.",
    githubUrl: undefined,
    websiteUrl: undefined,
    screenshots: [
      "screenshots/enseirb-schedule-notifier-1.png",
      "screenshots/enseirb-schedule-notifier-2.png",
      "screenshots/enseirb-schedule-notifier-3.png",
    ],
    deprecated: true,
    skills: [
      SkillName.Python,
      SkillName.Django,
      SkillName.JavaScript,
      SkillName.React,
      SkillName.PostgreSQL,
      SkillName.Docker,
    ],
  },
  {
    id: 10,
    name: "world-map",
    description:
      "World map with location markers of my travels and places I lived in.",
    githubUrl: undefined,
    websiteUrl: undefined,
    screenshots: ["screenshots/world-map-1.png"],
    deprecated: true,
    skills: [
      SkillName.Python,
      SkillName.Django,
      SkillName.JavaScript,
      SkillName.React,
      SkillName.PostgreSQL,
      SkillName.Docker,
    ],
  },
  {
    id: 7,
    name: "discord-dice-roller",
    description:
      "An open-source, lightweight, and easy-to-use dice-roller bot for discord.",
    githubUrl: "https://github.com/Jordan-Kowal/discord-dice-roller",
    websiteUrl: "https://jordan-kowal.github.io/discord-dice-roller/",
    screenshots: ["screenshots/discord-dice-roller-1.png"],
    deprecated: true,
    skills: [SkillName.Python],
  },
  {
    id: 8,
    name: "django-database-translation",
    description:
      "Package for handling database translation in a website with multiple languages.",
    githubUrl: "https://github.com/Jordan-Kowal/django-database-translation",
    websiteUrl: "https://pypi.org/project/django-database-translation/",
    screenshots: [],
    deprecated: true,
    skills: [SkillName.Python, SkillName.Django, SkillName.PostgreSQL],
  },
  {
    id: 9,
    name: "sudoku-manager",
    description:
      "My first project. Sudoku solver (and generator) using brute force algorithm.",
    githubUrl: "https://github.com/Jordan-Kowal/sudoku-manager",
    websiteUrl: "https://pypi.org/project/sudoku-manager/",
    screenshots: [],
    deprecated: true,
    skills: [SkillName.Python],
  },
];
